### PR TITLE
Meals app

### PR DESCRIPTION
**Pull request by Nisanth2003**
Name - Nisanth Reddy
Reg no :- 12101844
roll no:-04
Screenshot (1599)

### CODE REVIEW

**Comment by Aadeesh11** [comment]
You've used the network constructor for the image class! Try using the asset constructor as we are not fetching any images from network but instead they are saved(shipped) with the app itself.

**Comment by Nisanth2003** [comment]
Ok sir, got it, I will update it ASAP.

**Comment by Aadeesh11** [comment]
See the label, no more changes are allowed!

**Comment by Nisanth2003** [comment]
Ok sir, no problem I will edit it in my own repository for the future
opportunities thank you for the guidance

**Pull request closed without merging**
