### PR TITLE
meals

### PR DESCRIPTION
**Pull request by dikshaa1215**

### CODE REVIEW

**Comment by ItsAdityaKSingh** [comment]
Screenshot 2024-07-22 at 8 47 53 PM

Cannot see anything on Categories Screen

**Comment by ItsAdityaKSingh** [comment]
Also pls let me know your name and roll number

**Comment by dikshaa1215** [comment]
Diksha Verma
12218932

**Comment by dikshaa1215** [comment]
Sir, names u mentioned in the list Diksha Verma and diksha1215  are one and
the same, serial no. 3 and 16 respectively
Name - DIKSHA VERMA
Reg no. - 12218932

**Pull request closed without merging**
